mdn/css-examples

variable-fonts/grade.html, variable-fonts/italic.html, variable-fonts/optical-sizing.html, variable-fonts/sample-page.html, variable-fonts/slant.html
I've made some syntax updates to more accurately reflect the spec.
=> Syntax updates

counter-style-demo/css/style.css, counter-style-demo/index.html
Removes outdated warning about CSS `@counter-style`  being supported _only_  on Firefox 33.
=> Remove warning about Firefox 33 from @counter-style demo

learn/media-queries/grid.html
As the title suggests, the styling isn't properly showing for mobile screens without this viewport tag.
=> add viewport for mobile screens

learn/tasks/grid/marking.md
In https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grid_skills#Grid_Layout_Two there is an additional question:
> Can you now cause the first item to display on top without changing the order of items in the source?
I thought it would be useful to add at least one acceptable solution.
I admit that my text might be improved, as I was focusing more on the solution itself.
@chrisdavidmills I mention you because otherwise no one will approve/deny this
=> Adding a missing solution for an additional question

learn/tasks/position/marking.md
=> Fix a wrong link name in a marking guide

learn/rwd/float-based-rwd.html
In [Responsive Design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design#Flexible_grids) the example is not responsive on Chrome
@chrisdavidmills
=> Fix media query being always applied

learn/values-units/color-hex.html
Make box three text consistent with box one and two (missing #)
=> Make box three text consistent with box one and two (missing #)

learn/tasks/flexbox/marking.md
Task 2 is missing the solution to the additional question and Task 4 is missing the solution code.
I tested the updates in the live editors of the task page to make sure they are correct.
=> Improve Flexbox marking guide

images/image-set-type.html
=> add cross browser support for image-set() css ref in alternative image formats example

flow/block-inline/flex.html
I think the L in FLex should be uncapitalized. Sorry if it was on purpose.
=> fix case in flex example

learn/tasks/cascade/cascade-download.html, learn/tasks/cascade/cascade.html, learn/tasks/float/float1-download.html, learn/tasks/float/float1.html, learn/tasks/float/float2-download.html, learn/tasks/float/float2.html, learn/tasks/float/float3-download.html, learn/tasks/float/float3.html
Improve contrast of interactive examples like mentioned in issue [#2054](https://github.com/mdn/interactive-examples/issues/2054).
**important**: note pr [#15579](https://github.com/mdn/content/pull/15579) in mdn/content, where the images where changed accordingly, and pr #74 - ideally, these prs would have to be merged at the same time i think?
>with these changes of the color values, they conform now to the AAA standard according to WCAG
=> Improve contrast of interactive examples

learn/tasks/values/color-download.html, learn/tasks/values/color.html
setting the alpha value to "0.2" instead of ".2"
it's considered best practice and it's common in style guides like in google ones (https://google.github.io/styleguide/htmlcssguide.html#Leading_0s)
Note [pr #15579](https://github.com/mdn/content/pull/15579) in mdn/content, where I changed the image accordingly.
=> Best practice value for alpha channel and better contrast/visibility

learn/cascade/cascade-layers.html, learn/cascade/specificity-boxes.html, learn/tasks/cascade/cascade.html
Currently updating /en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance. This update reflects the change in that tutorial
=> Minor: updates specificity weights to reflect updated tutorial. Add cascade file

learn/tasks/cascade/cascade-download.html
Font names separated by spaces should be under quotes, so added quotes around the font family
Fixes : #51 font name without ' '
=> Added quotes to the font name

counter-style-demo/css/style.css, counter-style-demo/js/script.js
It fixes a mismatch in "symbolic" and "additive" types, which were showing different symbols than what was shown in code area. Similar issue was present in "numeric" type, which showed "." after each symbol, which it shouldn't be.
I also fixed symbols of "fixed" type, which used characters not supported by the browser.
=> counter-style-demo fixes

learn/tasks/selectors/pseudo.html
Firefox implicitly inserts \<tbody\> element to the table displayed on the page, while editable html doesn't include it.
In the task you need to select every other row of the table without modifying html. One way to do that is to write following selector:
```
table > th:nth-child(2n + 1) {
}
```
But because \<tr\> is wrapped in \<tbody\>, this selector doesn't work and it's not obvious why without looking in browser inspector.
I just wrapped all rows in \<tbody\> so you can see it in editable html.
=> fix(learn): wrap table rows in <tbody>

css-cookbook/sticky-footer-flexbox--download.html, css-cookbook/sticky-footer-flexbox.html
The sticky footer example contained a few errors listed below:
- The example CSS did not include the required CSS styles for the HTML and BODY tags.
- The example CSS set the `flex-shrink` on the header and footer, but not `flex-grow`
- Improper indentation on the closing div tag in the HTML.
- The textarea for the example CSS was too short, requiring resizing to see the full example code.
- The preview area was too tall, making it hard to view the example code.
- The page did not properly separate styles used for demonstration, and styles used in the recipe.
=> correcting sticky footer example

variable-fonts/font-weight.html
Apparently Chrome and Safari depend on declaring the `font-weight` range in the `@font-face` declaration for variable fonts to behave predictably. For this particular example, changing the font-weight of the element in Chrome had no effect.
=> variable-fonts/font-weight.html: Add font-weight range to @font-face declaration

css-cookbook/breadcrumb-navigation--download.html, css-cookbook/breadcrumb-navigation.html
- make breadcrumbs wrappable with `flex-wrap: wrap`
- don't hide list-style, margin and padding on ul in example
- links href with dummy hash `#` href
mdn/yari#5912
=> fix(cookbook-breadcrumb-navigation): make example responsive

learn/tasks/grid/marking.md
I just found a typo in marking.md file in css-examples/learn/tasks/grid.
Last paragraph : "flexbox" would be more appropriate, in this context.
=> fix typo in marking.md of css-examples/learn/tasks/grid

learn/values-units/color-hsla.html
This is the css-examples side of https://github.com/mdn/content/pull/23390.
=> Use hsl, not hsla

variable-fonts/grade.html, variable-fonts/italic.html, variable-fonts/optical-sizing.html, variable-fonts/sample-page.html, variable-fonts/slant.html, variable-fonts/weight.html, variable-fonts/width.html, visual-formatting/anonymous-block.html, visual-formatting/anonymous-flex.html, visual-formatting/line-boxes.html, web-fonts/basic-web-font.html
There are going to be 8 PRs. 
* ensure lang attribute set
* ensure charset set
* ensure viewport meta is set
* ensure title is included
In that order
* remove type=text on script and stylesheet; not needed
* remove unneeded prefixes in css
* remove reference to IE
* remove shivs
* remove IE compact statements
* likely some other stuff
=> Group 1: modernize content

display/multi-keyword/block-flow-root.html, display/multi-keyword/inline-block.html, display/multi-keyword/inline-flex.html, display/multi-keyword/multi-keyword-flex.html, display/multi-keyword/span-flex.html
This PR renames "two-value" syntax to "multi-keyword" syntax. In our content, we use "two-value" as the name, but in both BCD and the spec, it is defined as "multi-keyword".
Sister PR to https://github.com/mdn/content/pull/24344.
=> display: two-value -> multi-keyword

counter-style-demo/js/script.js
Found typos in the index, css, and js files for the counter-style demo page that made the devanagari list style not function properly. 
changed occurrences of 'devanagiri' to 'devanagari'
=> 'devanagiri' changed to 'devanagari'

learn/media-queries/grid.html
Fixes https://github.com/mdn/content/issues/24713
- add a margin such that when the width of the page is reduced, the grid item will not be directly in contact with the aside.
Before:
After:
=> Update CSS to fix margin bottom of learn/media-queries/grid.html

tools/color-picker/index.html, tools/color-picker/script.js, tools/color-picker/styles.css
Updated CSS to remove unneeded prefixing.
Updated CSS and JS to RGB() and HSL() from legacy RGBA() and HSLA()
Renamed HSV to HWB
was going to convert to flex/grid, but that is for a different day (though did start)
=> Colorpicker: modernize CSS & colors

learn/selectors/after-icon.html, learn/selectors/before.html
This PR adds semicolons after the last declarations appeared on [Pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements#generating_content_with_before_and_after) in order to eliminate possible distraction for learners with resprect to the CSS syntax.
Fixes https://github.com/mdn/content/issues/25274.
*Note:* It seems that the GitHub website editor also did something to the ends of the changed files. Do I have to patch them up?
=> Adding semicolons after the last declarations

types/filterfunctions.html
This PR adds a missing `}` in the filter functions demo [code](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function#examples).
Fixes https://github.com/mdn/content/issues/24874.
=> Adding missing `}` in the filter functions demo

modules/colors.html
Example for new CSS color module page.
=> New page: color modules example

modules/colors.html
=> Minor edit: add viewport meta tag

learn/tasks/backgrounds/backgrounds2-download.html
Changed <title> to say:
Backgrounds and Borders: Task 2
It is the second task during "Test your skills: background and borders".  The typo made me double-check that I had the right file downloaded.
=> Fixed typo in <title> element

tools/border-image-generator/index.html, tools/border-image-generator/styles.css
Fixes #79.
This PR also aligns the order of values of `border-image-repeat` to [that](https://w3c.github.io/csswg-drafts/css-backgrounds/#border-image-repeat) in the spec.
=> Add the `space` value to the options of `border-image-repeat`

tools/border-image-generator/script.js
This PR fixes the `repeat` values for the predefined samples in the border-image generator. The old values became mismatched after #129.
=> Fix `repeat` for predefined samples

modules/colors.html
The demo on https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors produces wrong results for the HWB colour model. For example, selecting black yields `hwb(0 0.0% 0.0%)`, which is actually red. The correct result is `hwb(0 0.0% 100.0%)`. Similarly, selecting a white colour yields the code for black, whereas a red colour results in `hwb(0 100.0% 100.0%)`. The white and black mixins should be zero, and in any case sum to at most 100%.
I did not understand where the formulas for W and B could have come from. The value called `hsv` in the original is one half the chroma value. I replaced it for the sake of better understanding.
=> Fixed incorrect conversion to HWB

modules/overflow.html
New example for CSS overflow module page.
=> CSS Modules example: overflow

modules/scroll_snap.html
similar to https://codepen.io/estelle/pen/JjmOpvm
=> New example: Scroll snap

flexbox/use-cases/split-navigation.html
- Fixes https://github.com/mdn/content/issues/13591
=> fix: use `gap` instead of margin for flex navigation

learn/overflow/auto.html, learn/overflow/block-overflow.html, learn/overflow/hidden.html, learn/overflow/scroll-y.html, learn/overflow/scroll.html
- Fixes https://github.com/mdn/content/issues/27975
If we update width we won't have to update `mdn/content` side. With width `350px` the overflow doesn't spill over the output area.
To test the change try the width in the live sample https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content#css_tries_to_avoid_data_loss
=> fix(CSS): too much overflow in the example output

learn/selectors/nesting.html
Created a example to show how CSS nesting can be used to create complex rules
This is being used in /content/files/en-us/learn/css/building_blocks/selectors/combinators/index.md
=> 27180 css nesting

learn/tasks/sizing/height-min-height-download.html
See https://github.com/mdn/content/issues/28901.
The substantive change here is to remove the `.preview` CSS rule, that's not relevant to the downloadable version of this example and that confused the reporter of https://github.com/mdn/content/issues/28901.
2 commits:
- https://github.com/mdn/css-examples/commit/e8c4e979b81fbfe38e05551f529f6f8c524c0022: Prettier formatting only
- https://github.com/mdn/css-examples/commit/09139b4117f8a2a2f7f319295e662be647f76f30: remove `.preview`
=> Fix content issue 28901

modules/generated_content.html
this example will be used by the CSS module page.
=> New example: generated content

modules/transforms.html
_(The below is copy/pasted from [the Content PR's](https://github.com/mdn/content/pull/30783) text.)_
1. Improves the existing CSS Transforms module with a powerful new interactive example and additional prose for context.
2. Implements a new guide related to CSS transforms called "Styling animated buttons with CSS transforms"
Main motivation: Improving our documentation as a part of [the Interop 2023 project](https://github.com/mdn/mdn/issues/416).
- `content` PR (for additional module prose and new guide): https://github.com/mdn/content/pull/30783
- `css-examples` PR (for the module page's "CSS transforms in action" interactive example section): https://github.com/mdn/css-examples/pull/160
- `yari` PR (for sidebar changes): https://github.com/mdn/yari/pull/10127
Once these three PRs are …
=> CSS Transforms Module Interactive Example

feature-queries/and.html, feature-queries/not.html, feature-queries/or.html
grid and flex are supported. Font smoothing is a little bit more questionable. Also includes a prefixed property.
=> modernize example

feature-queries/or.html
always is not a valid value for the experimental prefixed property. also, improved grammar
=> fixed error: -webkit-font-smoothing value

feature-queries/simple.html
green for support is more intuitive than red.
=> color and border style
